/* *********************************************************************
 * PVMOS Header file generated by MeshHasher, DO NOT EDIT              *
 *                                                                     *
 * What is this?                                                       *
 * PVMOS binary mesh format is not guaranteed to be compatable with    *
 * future or past PVMOS versions. For simplicity the format is a       *
 * straightforward binary dump of the mesh data structure. Obviosously *
 * if anything changes in the data structures this format must change. *
 * To verify compatibility we thus need some sort of data structure    *
 * versioning. The coolest way is obviously to generate a data         *
 * structure signature so PVMOS can automatically detect incompatible  *
 * changes.                                                            *
 * MeshHasher generates an md5 sum of a simple mesh and stores the     *
 * hash in a header file for inclusion in PVMOS. The hash is included  *
 * in the binary mesh files to verify compatibility.                   *
 *                                                                     *
 ***********************************************************************
 * Current PVMOS mesh data structure signature:                        *
 *---------------------------------------------------------------------*
 *                                                                     *
 *                  608b0588687d5cba2ee13fc6c25063d2                   *
 *                                                                     *
 * *********************************************************************/
#define _HAS_MESHHASH
int NMESHHASH=16;
unsigned char MESHHASH[] = {
	0x60,
	0x8b,
	0x05,
	0x88,
	0x68,
	0x7d,
	0x5c,
	0xba,
	0x2e,
	0xe1,
	0x3f,
	0xc6,
	0xc2,
	0x50,
	0x63,
	0xd2
};
