/* *********************************************************************
 * PVMOS Header file generated by MeshHasher, DO NOT EDIT              *
 *                                                                     *
 * What is this?                                                       *
 * PVMOS binary mesh format is not guaranteed to be compatable with    *
 * future or past PVMOS versions. For simplicity the format is a       *
 * straightforward binary dump of the mesh data structure. Obviosously *
 * if anything changes in the data structures this format must change. *
 * To verify compatibility we thus need some sort of data structure    *
 * versioning. The coolest way is obviously to generate a data         *
 * structure signature so PVMOS can automatically detect incompatible  *
 * changes.                                                            *
 * MeshHasher generates an md5 sum of a simple mesh and stores the     *
 * hash in a header file for inclusion in PVMOS. The hash is included  *
 * in the binary mesh files to verify compatibility.                   *
 *                                                                     *
 ***********************************************************************
 * Current PVMOS mesh data structure signature:                        *
 *---------------------------------------------------------------------*
 *                                                                     *
 *                  ef703ab7f8e32da307418775a423c7c2                   *
 *                                                                     *
 * *********************************************************************/
#define _HAS_MESHHASH
int NMESHHASH=16;
unsigned char MESHHASH[] = {
	0xef,
	0x70,
	0x3a,
	0xb7,
	0xf8,
	0xe3,
	0x2d,
	0xa3,
	0x07,
	0x41,
	0x87,
	0x75,
	0xa4,
	0x23,
	0xc7,
	0xc2
};
