/* *********************************************************************
 * PVMOS Header file generated by MeshHasher, DO NOT EDIT              *
 *                                                                     *
 * What is this?                                                       *
 * PVMOS binary mesh format is not guaranteed to be compatable with    *
 * future or past PVMOS versions. For simplicity the format is a       *
 * straightforward binary dump of the mesh data structure. Obviosously *
 * if anything changes in the data structures this format must change. *
 * To verify compatibility we thus need some sort of data structure    *
 * versioning. The coolest way is obviously to generate a data         *
 * structure signature so PVMOS can automatically detect incompatible  *
 * changes.                                                            *
 * MeshHasher generates an md5 sum of a simple mesh and stores the     *
 * hash in a header file for inclusion in PVMOS. The hash is included  *
 * in the binary mesh files to verify compatibility.                   *
 *                                                                     *
 ***********************************************************************
 * Current PVMOS mesh data structure signature:                        *
 *---------------------------------------------------------------------*
 *                                                                     *
 *                  b9e0e7b8e0a588845f1e68a957e9acb2                   *
 *                                                                     *
 * *********************************************************************/
#define _HAS_MESHHASH
int NMESHHASH=16;
unsigned char MESHHASH[] = {
	0xb9,
	0xe0,
	0xe7,
	0xb8,
	0xe0,
	0xa5,
	0x88,
	0x84,
	0x5f,
	0x1e,
	0x68,
	0xa9,
	0x57,
	0xe9,
	0xac,
	0xb2
};
