/* *********************************************************************
 * PVMOS Header file generated by MeshHasher, DO NOT EDIT              *
 *                                                                     *
 * What is this?                                                       *
 * PVMOS binary mesh format is not guaranteed to be compatable with    *
 * future or past PVMOS versions. For simplicity the format is a       *
 * straightforward binary dump of the mesh data structure. Obviosously *
 * if anything changes in the data structures this format must change. *
 * To verify compatibility we thus need some sort of data structure    *
 * versioning. The coolest way is obviously to generate a data         *
 * structure signature so PVMOS can automatically detect incompatible  *
 * changes.                                                            *
 * MeshHasher generates an md5 sum of a simple mesh and stores the     *
 * hash in a header file for inclusion in PVMOS. The hash is included  *
 * in the binary mesh files to verify compatibility.                   *
 *                                                                     *
 ***********************************************************************
 * Current PVMOS mesh data structure signature:                        *
 *---------------------------------------------------------------------*
 *                                                                     *
 *                  3ffaeef77be9d2a92692d73d460c3f6e                   *
 *                                                                     *
 * *********************************************************************/
#define _HAS_MESHHASH
int NMESHHASH=16;
unsigned char MESHHASH[] = {
	0x3f,
	0xfa,
	0xee,
	0xf7,
	0x7b,
	0xe9,
	0xd2,
	0xa9,
	0x26,
	0x92,
	0xd7,
	0x3d,
	0x46,
	0x0c,
	0x3f,
	0x6e
};
